package main

import (
	"log"
)

func main() {
	// InitializeApp is defined in wire_gen.go (generated by Wire).
	// It automatically loads Config, connects to Postgres/Redis, creates the Logger,
	// and assembles the Server struct for you.
	srv, err := InitializeApp()
	if err != nil {
		log.Fatalf("❌ Failed to initialize app: %v", err)
	}

	// Start the HTTP server
	if err := srv.Run(); err != nil {
		log.Fatalf("❌ Server crashed: %v", err)
	}
}