// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dhyey3187/finxplore-api/internal/config"
	"github.com/Dhyey3187/finxplore-api/internal/database"
	"github.com/Dhyey3187/finxplore-api/internal/logger"
	"github.com/Dhyey3187/finxplore-api/internal/server"
)

// Injectors from wire.go:

// InitializeApp is the blueprint for the Wire tool.
func InitializeApp() (*server.Server, error) {
	configConfig := config.LoadConfig()
	zapLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectPostgres(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := database.ConnectRedis(configConfig)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(configConfig, zapLogger, db, client)
	return serverServer, nil
}
