// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dhyey3187/finxplore-api/api/handler"
	"github.com/Dhyey3187/finxplore-api/api/repository"
	"github.com/Dhyey3187/finxplore-api/api/routes"
	"github.com/Dhyey3187/finxplore-api/api/service"
	"github.com/Dhyey3187/finxplore-api/internal/config"
	"github.com/Dhyey3187/finxplore-api/internal/database"
	"github.com/Dhyey3187/finxplore-api/internal/logger"
	"github.com/Dhyey3187/finxplore-api/internal/server"
)

// Injectors from wire.go:

// InitializeApp is the blueprint for the Wire tool.
func InitializeApp() (*server.Server, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectPostgres(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	client, err := database.ConnectRedis(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	cacheRepository := repository.NewCacheRepository(client)
	userService := service.NewUserService(userRepository, cacheRepository, configConfig)
	authHandler := handler.NewAuthHandler(userService)
	userRoutes := routes.NewUserRoutes(authHandler)
	routesRoutes := routes.NewRoutes(userRoutes)
	serverServer := server.NewServer(configConfig, zapLogger, db, client, routesRoutes)
	return serverServer, nil
}
